### ISSUE TITLE
Cannot run grunt patternlab:*

### ISSUE THREAD

**Issue by juanfernandes** [pattern-lab/edition-node-grunt#33]
I am using Edition Node Grunt `v2.12.0` on `Linux`, with Node `v10.6.0`.

##### Expected Behavior
Running grunt patternlab:serve runs pattern lab

##### Actual Behavior
Error
====[ Pattern Lab / Node - v2.12.0 ]====

Loading "Gruntfile.js" tasks...ERROR
>> TypeError: Cannot read property 'options' of undefined
>>   at pluginInit (/home/juanfernandes/sites/design-framework/node_modules/plugin-node-tab/index.js:64:66)
>>   at initializePlugins (/home/juanfernandes/sites/design-framework/node_modules/patternlab-node/core/lib/patternlab.js:135:7)
>>   at patternlab_engine (/home/juanfernandes/sites/design-framework/node_modules/patternlab-node/core/lib/patternlab.js:183:3)
>>   at Object.module.exports (/home/juanfernandes/sites/design-framework/Gruntfile.js:24:36)
>>   at loadTask (/home/juanfernandes/sites/design-framework/node_modules/grunt/lib/grunt/task.js:315:10)
>>   at Task.task.init (/home/juanfernandes/sites/design-framework/node_modules/grunt/lib/grunt/task.js:434:5)
>>   at Object.grunt.tasks (/home/juanfernandes/sites/design-framework/node_modules/grunt/lib/grunt.js:111:8)
>>   at Object.module.exports [as cli] (/home/juanfernandes/sites/design-framework/node_modules/grunt/lib/grunt/cli.js:27:9)
>>   at Object.<anonymous> (/usr/local/lib/node_modules/grunt-cli/bin/grunt:44:20)
>>   at Module._compile (internal/modules/cjs/loader.js:689:30)
>>   at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
>>   at Module.load (internal/modules/cjs/loader.js:599:32)
>>   at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
>>   at Function.Module._load (internal/modules/cjs/loader.js:530:3)
>>   at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
>>   at startup (internal/bootstrap/node.js:236:19)
>>   at bootstrapNodeJSCore (internal/bootstrap/node.js:560:3)

Running tasks: patternlab:serve
Warning: Task "patternlab:serve" not found. Use --force to continue.

My gruntfile: 

/******************************************************
 * PATTERN LAB NODE
 * EDITION-NODE-GRUNT
 * The grunt wrapper around patternlab-node core, providing tasks to interact with the core library and move supporting frontend assets.
******************************************************/

module.exports = function (grunt) {

  var path = require('path'),
      argv = require('minimist')(process.argv.slice(2));

  // load all grunt tasks
  grunt.loadNpmTasks('grunt-contrib-copy');
  grunt.loadNpmTasks('grunt-contrib-watch');
  grunt.loadNpmTasks('grunt-browser-sync');
  grunt.loadNpmTasks('grunt-contrib-sass');

  /******************************************************
   * PATTERN LAB CONFIGURATION
  ******************************************************/

  //read all paths from our namespaced config file
  var config = require('./patternlab-config.json'),
    pl = require('patternlab-node')(config);

  function paths() {
    return config.paths;
  }

  function getConfiguredCleanOption() {
    return config.cleanPublic;
  }

  grunt.registerTask('patternlab', 'create design systems with atomic design', function (arg) {

    if (arguments.length === 0) {
      pl.build(function(){}, getConfiguredCleanOption());
    }

    if (arg && arg === 'version') {
      pl.version();
    }

    if (arg && arg === "patternsonly") {
      pl.patternsonly(function(){},getConfiguredCleanOption());
    }

    if (arg && arg === "help") {
      pl.help();
    }

    if (arg && arg === "liststarterkits") {
      pl.liststarterkits();
    }

    if (arg && arg === "loadstarterkit") {
      pl.loadstarterkit(argv.kit, argv.clean);
    }

    if (arg && (arg !== "version" && arg !== "patternsonly" && arg !== "help" && arg !== "starterkit-list" && arg !== "starterkit-load")) {
      pl.help();
    }
  });

  grunt.initConfig({

    /******************************************************
     * COPY TASKS
    ******************************************************/
    copy: {
      main: {
        files: [
          { expand: true, cwd: path.resolve(paths().source.js), src: '**/*.js', dest: path.resolve(paths().public.js) },
          { expand: true, cwd: path.resolve(paths().source.js), src: '**/*.js.map', dest: path.resolve(paths().public.js) },
          { expand: true, cwd: path.resolve(paths().source.css), src: '**/*.css', dest: path.resolve(paths().public.css) },
          { expand: true, cwd: path.resolve(paths().source.css), src: '**/*.css.map', dest: path.resolve(paths().public.css) },
          { expand: true, cwd: path.resolve(paths().source.images), src: '**/*', dest: path.resolve(paths().public.images) },
          { expand: true, cwd: path.resolve(paths().source.fonts), src: '**/*', dest: path.resolve(paths().public.fonts) },
          { expand: true, cwd: path.resolve(paths().source.root), src: 'favicon.ico', dest: path.resolve(paths().public.root) },
          { expand: true, cwd: path.resolve(paths().source.styleguide), src: ['*', '**'], dest: path.resolve(paths().public.root) },
          // slightly inefficient to do this again - I am not a grunt glob master. someone fix
          { expand: true, flatten: true, cwd: path.resolve(paths().source.styleguide, 'styleguide', 'css', 'custom'), src: '*.css)', dest: path.resolve(paths().public.styleguide, 'css') }
        ]
      }
    },
    /******************************************************
     * SERVER AND WATCH TASKS
    ******************************************************/
    watch: {
      all: {
        files: [
          path.resolve(paths().source.scss + '**/*.scss'),
          // path.resolve(paths().source.css + '**/*.css'),
          path.resolve(paths().source.styleguide + 'css/*.css'),
          path.resolve(paths().source.patterns + '**/*'),
          path.resolve(paths().source.fonts + '/*'),
          path.resolve(paths().source.images + '/*'),
          path.resolve(paths().source.data + '*.json'),
          path.resolve(paths().source.js + '/*.js'),
          path.resolve(paths().source.root + '/*.ico')
        ],
        tasks: ['default', 'bsReload:css']
      }
    },
    sass: {
      options: {
        style: 'expanded'
      },
      dist: {
        files: {
          'source/css/style.css': 'source/scss/style.scss'
        }
      }
    },
    browserSync: {
      dev: {
        options: {
          server:  path.resolve(paths().public.root),
          watchTask: true,
          watchOptions: {
            ignoreInitial: true,
            ignored: '*.html'
          },
          snippetOptions: {
            // Ignore all HTML files within the templates folder
            blacklist: ['/index.html', '/', '/?*']
          },
          plugins: [
            {
              module: 'bs-html-injector',
              options: {
                files: [path.resolve(paths().public.root + '/index.html'), path.resolve(paths().public.styleguide + '/styleguide.html')]
              }
            }
          ],
          notify: {
            styles: [
              'display: none',
              'padding: 15px',
              'font-family: sans-serif',
              'position: fixed',
              'font-size: 1em',
              'z-index: 9999',
              'bottom: 0px',
              'right: 0px',
              'border-top-left-radius: 5px',
              'background-color: #1B2032',
              'opacity: 0.4',
              'margin: 0',
              'color: white',
              'text-align: center'
            ]
          }
        }
      }
    },
    bsReload: {
      css: path.resolve(paths().public.root + '**/*.css')
    }
  });

  /******************************************************
   * COMPOUND TASKS
  ******************************************************/

  grunt.registerTask('default', ['patternlab', 'sass', 'copy:main']);
  grunt.registerTask('patternlab:build', ['patternlab', 'sass', 'copy:main']);
  grunt.registerTask('patternlab:watch', ['patternlab', 'sass', 'copy:main', 'watch:all']);
  grunt.registerTask('patternlab:serve', ['patternlab', 'sass', 'copy:main', 'browserSync', 'watch:all']);
};

##### Steps to Reproduce
I cd into my sites/design-framework folder and run: `grunt patternlab:serve`

**Comment by juanfernandes** [comment]
I've tried another instance of Pattern Lab, running the same PL version and that works, so the issue is not with PL, but maybe a plug in?

**Comment by juanfernandes** [comment]
The issue was being caused by `plugin-node-tab`- I had created a new branch to test adding this plugin, but couldnt get it to work, so deleted the branch, but for some reason the plugin was still in node_modules, but because there was no options for it in config, it was causing an error.
